version: '3.8'

services:
  django:
    build: .
    container_name: p13_openclassrooms
    restart: always
    command:
      - python3
      - manage.py
      - runserver
    ports:
      - '8000:8000'
    volumes:
        - .:/code
