version: '3.8'

services:
  django:
    build: .
    container_name: P13_OpenClassrooms
    image: circleci/python:latest
    restart: always
    command:
      - python3
      - manage.py
      - runserver
    ports:
      - '8000:8000'
    volumes:
        - .:/code
    env_file:
      - .env


