version: '3.8'

services:
  django:
    build: .
    container_name: P13_OpenClassrooms
    restart: always
    command:
      - python3
      - manage.py
      - runserver
    ports:
      - '8000:8000'
    volumes:
        - .:/code
    environment:
      DOCKERHUB_USER: DOCKERHUB_USER
      DOCKERHUB_PASSWORD: DOCKERHUB_PASSWORD


