version: 2.1


jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.10.2
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: "Install dependencies and create virtual environnements"
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: "Linting"
          command: |
            source venv/bin/activate
            flake8
      - run:
          name: "Run tests"
          command: |
            source venv/bin/activate
            pytest

  containerize:
    docker:
      - image: cimg/python:3.10.2
    resource_class: medium
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Containerize
          command: |
            echo "${DOCKERHUB_PASSWORD}" | docker login --username ${DOCKERHUB_USER} --password-stdin
            docker build -t oc_lettings_site .
            docker tag oc_lettings_site ${DOCKERHUB_USER}/oc_lettings_site:$CIRCLE_SHA1
            docker push ${DOCKERHUB_USER}/oc_lettings_site:$CIRCLE_SHA1
            docker pull ${DOCKERHUB_USER}/oc_lettings_site:$CIRCLE_SHA1

  deploy:
    docker:
      - image: cimg/python:3.10.2
    resource_class: medium
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: 'Docker Image to Heroku'
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku config:set DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY -a $HEROKU_APP_NAME
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku config:set DEBUG=0 -a $HEROKU_APP_NAME
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push -a $HEROKU_APP_NAME web
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a $HEROKU_APP_NAME web
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku run python manage.py migrate -a $HEROKU_APP_NAME
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku run python manage.py loaddata data.json -a $HEROKU_APP_NAME

workflows:
  main:
    jobs:
      - build_and_test
      - containerize:
          requires:
            - build_and_test
      - deploy:
          requires:
            - build_and_test
            - containerize
