version: 2.1

orbs:
  python: circleci/python@2.1.1


jobs:
  build-and-test:
    executor: python/default
    resource_class: small
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Linting
          command: ./venv/bin/activate & flake8
      - run:
          name: Run tests
          command: ./venv/bin/activate & pytest
