version: 2.1


jobs:
  build_and_test:
    docker:
      - image: circleci/python:latest
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: "Install dependencies and create virtual environnements"
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: "Linting"
          command: |
            source venv/bin/activate
            flake8
      - run:
          name: "Run tests"
          command: |
            source venv/bin/activate
            pytest

  containerize:
    docker:
      - image: circleci/python:latest
    resource_class: medium
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Containerize
          command: |
            echo "${DOCKERHUB_PASSWORD}" | docker login --username ${DOCKERHUB_USER} --password-stdin
            docker build -t oc_lettings_site .
            docker tag oc_lettings_site ${DOCKERHUB_USER}/oc_lettings_site:$CIRCLE_SHA1
            docker push ${DOCKERHUB_USER}/oc_lettings_site:$CIRCLE_SHA1

workflows:
  main:
    jobs:
      - build_and_test
      - containerize:
          requires:
            - build_and_test
