version: 2.1


jobs:
  build_and_test:
    docker:
      - image: "circleci/python:latest"
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: "Install dependencies and create virtual environnements"
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: "Linting"
          command: |
            source venv/bin/activate
            flake8
      - run:
          name: "Run tests"
          command: |
            source venv/bin/activate
            pytest

  containerize:
    docker:
      - image: "circleci/python:latest"
    resource_class: medium
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Containerize
          command: |
            docker build -t p13_openclassrooms .
            docker tag p13_openclassrooms $DOCKERHUB_USER/$DOCKERHUB_REPO:$CIRCLE_SHA1
            docker push $DOCKERHUB_USER/$DOCKERHUB_REPO:$CIRCLE_SHA1
            echo "${DOCKERHUB_PASSWORD}" | docker login --username ${DOCKERHUB_USER} --password-stdin

workflows:
  main:
    jobs:
      - build_and_test
      - containerize:
          requires:
            - build_and_test
