version: 2.1


jobs:
  build:
    working_directory: ~/.circleci
    docker:
      - image: "circleci/python:latest"
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
  test:
    working_directory: ~/.circleci
    docker:
      - image: "circleci/python:latest"
    steps:
      - checkout
      - run: python3 manage.py pytest


  containerize:
    docker:
      - image: "circleci/python:latest"
    resource_class: medium
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Containerize
          command: docker compose up


workflows:
  main:
    jobs:
      - build
      - containerize:
          requires:
            - build
      - test:
          requires:
            - build
            - containerize
