version: 2.1


jobs:
  build:
    working_directory: ~/.circleci
    docker:
      - image: "circleci/python:3.9.13"
    steps:
      - checkout
      - run: python3 manage.py runserver
  test:
    working_directory: ~/.circleci
    docker:
      - image: "circleci/python:3.9.13"
    steps:
      - checkout
      - run: python3 manage.py pytest

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build

