version: 2.1


jobs:
  build:
    working_directory: ~/.circleci
    docker:
      - image: "circleci/python:latest"
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: |
          python3 -m venv venv
          ./venv/bin-activate
          pip install -r requirements.txt
          python3 manage.py runserver
  test:
    working_directory: ~/.circleci
    docker:
      - image: "circleci/python:3.9.13"
    steps:
      - checkout
      - run: python3 manage.py pytest

workflows:
  build_and_test:
    jobs:
      - build
